# Card data part 3 (exec'd after cards2.py): backlog

API = [
    ("T-60", "Placement in the model (anchor rect and side)", "S", ["T-15"],
     "`needs: [\"placement\"]` → the host sends `update({type: \"placement\", side, anchor})` before each reposition, computed the way `placePopup` places the popup (" + L("extension/content.js", 1855, 1901, "placePopup/positionPopup") + ").",
     "Tategaki's tail points at the hovered word; no DOM reads of the page.", ["c15"],
     "c15 gap 1 (`view.anchor`, 10-line [host-anchor.patch](https://github.com/bee-san/hachidori/tree/evidence/issue-330-theme-manga-vertical/docs/evidence/issue-330/themes/manga-vertical)); placement side also asked in c12/c13."),
    ("T-61", "Declared theme keys", "M", ["T-15"],
     "Manifest `keys: [{ key, command, label }]`; the core routes unmodified printable keys to `view.update({type: \"key\", command})` only while the popup has focus and never in text fields; user keybinds always win; Escape stays the core close keybind. Needs open question 8.",
     "Retro's j/k, Learner Focus 1/2/0, Tango A/B/C and denshi's Backspace work without stealing user keybinds.", ["c12", "c17", "c19", "c24"],
     "c12 gap 1 (`onKey`), c17 gap 3, c19 gap 6, c24 gap 1 (Escape consumed by the capture listener, " + L("extension/content.js", 4256, None, "content.js:4256") + ")."),
    ("T-62", "`ctx.actions.copyText`", "S", ["T-16"],
     "`copyText(text)` inside a user gesture on a renderer control; the core calls `navigator.clipboard.writeText`.",
     "Sentence Context's copy button works; lint still forbids `navigator` in renderers.", ["c13"],
     "c13 gap 2; harness note: `Browser.grantPermissions` with clipboardReadWrite + clipboardSanitizedWrite in headless Chrome."),
    ("T-63", "Theme memory: page state rules, optional session/storage", "M", ["T-19", "T-15"],
     "Document now (contract): module state lives for the page and is dropped on renderer switch. Then, if open question 7 says yes: `ctx.session` (per tab, never synced) and/or `ctx.storage` (namespaced per slug, JSON, ≤ 64 KiB, written through the service worker like hd_themes_cas).",
     "Learner Focus \"Knew it\", Tango's pet and denshi history persist as approved; the Store says \"history is per page\" otherwise.", ["c12", "c19", "c24", "c10"],
     "c12 gap 2, c19 gap 2, c24 gap 5, c10 gap 3."),
    ("T-64", "Headword kanji data (`needs: [\"headwordKanji\"]`)", "M", ["T-15"],
     "The core looks up each kanji of the primary headword with the existing kanji query (as " + L("extension/content.js", 3109, 3211, "executeKanjiRequest") + " does) and sends `update({type: \"headwordKanji\", map})`.",
     "Kanji Atlas tiles and the Learner Focus kanji table fill without clicking each kanji.", ["c12", "c10"],
     "c12 gap 3; c10 (tiles fill in only after visiting a kanji)."),
    ("T-65", "Sentence segments (`needs: [\"sentenceSegments\"]`)", "S", ["T-15"],
     "`model.source.segments`: the scanner's word boundaries over the sentence, computed once by the core.",
     "Sentence Context marks dictionary words without a heuristic.", ["c13"], "c13 gap 7."),
]
for cid, title, size, deps, goal, acc, src, note in API:
    card(id=cid, phase=6, title=title, owner="core agent", size=size, deps=deps, goal=goal,
         files=[("contract PR", "`docs/themes/contract.md`", "additive change, modelVersion/apiVersion stay 1")],
         steps=["Contract amendment first (a `contract` PR), then the implementation."],
         tests=["host tests + the consuming renderer's contract run"], accept=[acc], short=acc, src=src, notes=[note])

PROPOSALS = [
    ("T-70", "kanji-atlas", "Kanji Atlas", "c10", None,
     "The headword becomes a rail of kanji tiles (stroke ring, the reading this word uses, JLPT/grade/strokes, top meanings); the kanji view is an atlas card with \"Met on this page\".",
     ["T-30", "T-64"], "furigana segments + kanji data from the model (not `aria-label`/`dt`/`data-sc-bee-role` scraping); per-node `ctx.setVariable`; Mincho fonts"),
    ("T-71", "learner-focus", "Learner Focus", "c12", "c14",
     "Progressive disclosure: the popup asks \"did you know it?\" before it tells you (layers 0–4, reading line with pitch, kanji table, \"Knew it\").",
     ["T-30", "T-61", "T-63", "T-64"], "keys 1/2/0, memory for \"Knew it\", headword kanji data, `layout.size: content`"),
    ("T-72", "sentence-context", "Sentence Context (文脈) + sentence-context-dark", "c13", None,
     "The top band is the sentence you were reading (sesame-dot emphasis), then the deconjugation trail as chips and a preview of the Anki sentence field; `-dark` becomes a variant.",
     ["T-30", "T-62", "T-65"], "`model.source`, `reason`, copyText, sentence segments"),
    ("T-73", "manga-vertical", "Tategaki (manga-vertical) + manga-vertical-night", "c15", None,
     "A vertical-rl margin note beside the speech bubble with a tail pointing at the word; `-night` becomes a variant.",
     ["T-30", "T-60"], "anchor rect/side, `@starting-style`, tablist orientation, renderer-owned Back disclosures"),
    ("T-74", "geocities-y2k", "Geocities Y2K", "c16", "c18",
     "Every word gets its own 1999 homepage: marquee, visitor counter (the lookup count), web ring, guestbook.",
     ["T-30"], "`lookupStats`/`actionState` update events instead of CSS-animation polling; `@keyframes`"),
    ("T-75", "retro-terminal", "Retro Terminal", "c17", None,
     "An amber phosphor candidate list with j/k selection, pitch as `LHL` and a status line.",
     ["T-30", "T-61"], "keys, `setCurrentEntry`, structured pitch/frequency data, lookup-stats slot"),
    ("T-76", "tamagotchi-lcd", "Tango Pet LCD", "c19", "c20",
     "The popup is a virtual pet you feed with the words you mine (Anki success grows the pet); an LCD pager with A/B/C keys.",
     ["T-30", "T-61", "T-63"], "`actionState` events, session memory, keys; must cut the backdrop-blur cost (+11 ms first / +31 ms complete measured) to pass the end-to-end budget"),
    ("T-77", "rpg-dialogue", "RPG Dialogue", "c21", None,
     "A 16-bit JRPG message window that pages through senses with a typewriter and a command menu.",
     ["T-30"], "`ctx.schedule`, `reason`, `@keyframes`, nested lookups inside typed text (`data-hd-scan`)"),
    ("T-78", "omikuji-shrine", "Omikuji Shrine", "c22", "c23",
     "Every lookup is a fortune slip graded by the word's frequency rank.",
     ["T-30"], "frequencies with `mode` (rank- vs occurrence-based), `env.reducedMotion`; `js.summary` must shrink from 400 to ≤ 200 characters"),
    ("T-79", "denshi-jisho", "電子辞書 (denshi-jisho)", "c24", "c25",
     "The popup is a grey handheld electronic dictionary: keys, LCD list/detail screens, history.",
     ["T-30", "T-61"], "keys (Backspace = 戻る; Escape stays close), `setCurrentEntry`, per-page history; `js.summary` 377 → ≤ 200"),
]
for cid, slug, name, cm, cm2, concept, deps, needs in PROPOSALS:
    branch = f"evidence/issue-330-theme-{slug}"
    src = [cm] + ([cm2] if cm2 else [])
    card(id=cid, phase=6, title=f"Port the {name} proposal as a renderer", owner="renderer agent", size="M", deps=deps, repo="hachidori-theme-store",
         goal=concept + " Port it from the onRender prototype to its own popup on the v1 contract (c26/c28): build from the model, never scrape or hide Default.",
         files=[("new", f"`themes/{slug}/{{theme.yaml,renderer.js,renderer.css,README.md,screenshot.png}}`", "from the proposal's files"),
                ("evidence", EV(branch, f"docs/evidence/issue-330/themes/{slug}", branch), "screenshots, capture script, evidence.json, benchmark")],
         steps=[f"Needs: {needs}.", "Re-verify the proposal's accessibility table (contrast, forced-colors, reduced motion, keyboard) on the port."],
         tests=["themes CI gates (validate, lint, contract, render, benchmark)"],
         accept=["Gates green including the end-to-end budget; screenshots comparable to the proposal; bee-san approves inclusion."],
         short="Renderer port; all gates green; bee-san approves", src=src)
